### ISSUE TITLE
Release data on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [aryopg/decore#5]
Hello @aryopg 🤗

I'm Niels and work as ML engineer at Hugging Face. I discovered your work as it got featured in AK's daily papers: https://huggingface.co/papers/2410.18860. The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the data found [here](https://github.com/aryopg/decore/tree/main/data) on https://huggingface.co/datasets?Hosting on Hugging Face will give you more visibility/enable better discoverability, and will also allow people to do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org/your-data")
```

If you're down, leaving a guide here: https://huggingface.co/docs/datasets/loading#json

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

After uploaded, we can also link the datasets to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your work.

What do you think?

Kind regards,

Niels

**Comment by aryopg** [comment]
Hi Niels, thanks for noticing our work!

I'd be very down to host my data on HF. But I'd like to clarify that these datasets are not mine and are also available on HF. These datasets were downloaded locally (and pushed to Github) due to AstraZeneca's internal policy at the time of the project development.

Alternatively, I can perhaps create a suite of datasets on the HF dataset page that I think is important to evaluate hallucinations. But, I can't take credit for the datasets themselves. What do you think?

Best,
Aryo
