### ISSUE TITLE
About the model used in truthfulqa generation eval

### ISSUE THREAD

**Issue by AlmightYouth** [aryopg/decore#6]
Thanks for your outstanding work. In your description, you used the fine-tuned davinci-002 model for the generative discrimination of the TruthfulQA dataset, but it seems that thedavinci-002 model is no longer supported for API fine-tuning.How exactly did you fine-tune it?

**Comment by aryopg** [comment]
Thanks for the kind words @AlmightYouth ! At the time of the project, `davinci-002` was actually still available. I just checked the OpenAI platform, and you are right `davinci-002` is no longer on the list.

You can try replacing it with a newer model as long as you can get the logprobs of the generation. In terms of the cost, I would imagine that it won't be far more expensive compared to `davinci-002` fine-tunings (I spent $43 to fine-tune both models).

I'd be curious to know once you have results from using newer judge models! 😄 

_Note: that we had to use `davinci-002` instead of `curie` which was used in the original TruthfulQA paper. The [ITI paper](https://github.com/likenneth/honest_llama) also uses `davinci-002`._
